# This is a basic workflow to help you get started with Actions

name: Slither

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, hardhat ]
  pull_request:
    branches: [ main, hardhat ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: slither-static-analysis
        # You may pin to the exact commit or the version.
        # uses: luisfontes19/slither-static-analysis-action@d67bb3f95bbbe9f5ae686709697f1e7d55e814ae
        uses: luisfontes19/slither-static-analysis-action@v0.3.3
        with:
          # By default the action will run npm install on the source folder. Set this variable as false to disable it
          run-npm-install: true # optional, default is true
          # Specify slither version to use. It will download it from official github project.
          slither-version: 0.8.1 # optional, default is 0.6.14
          # Action will fail if the number of High findings is equal or bigger then this value (0 to disable)
          high-threshold: 1 # optional, default is 1
          # Action will fail if the number of Medium findings is equal or bigger then this value (0 to disable)
          medium-threshold: 1 # optional, default is 1
          # Action will fail if the number of Low findings is equal or bigger then this value (0 to disable)
          low-threshold: 1 # optional, default is 1
          # Action will fail if then number of Informative findings is equal or bigger then this value (0 to disable)
          informative-threshold: 10 # optional, default is 10
          # Action will fail if then number of Optimization findings is equal or bigger then this value (0 to disable)
          optimization-threshold: 10 # optional, default is 1
          # THe path for the smart contracts' project.
          projectPath: . # optional, default is .
          # Extra slither parameters to use when running the tool
          slither-params: --filter-paths "node_modules" # optional
